
language: java
jdk:
  -openjdk13
  
addons:
  sonarcloud:
    organization: jdgifgiegifugrsigskjsgeirgsrhjrskjdhfsihusugeuhdsskhyds
    token: 733f8eebbe9e66d7ec478f043dd0aadf15d2b697

script: 
  - ant build
  - sonar-scanner
